### ISSUE TITLE
Building on Raspberry pi (python 2.7) fails

### ISSUE THREAD

**Issue by bkoblenz** [anntzer/redeal#13]
This seems like an amazing program and very well written.  Thanks.

I was going to add a couple of features that (I think) I need and I do most of my development on Debian linux raspberry pi devices and when I tried to build there I failed.

The features I wanted to add were:
    a) separate the notion of how many hands to deal from the notion of how many hands to deal that meet the specified criteria.  My goal is to say, generate 32 hands, with 10 of them (randomly interspersed) that meet restrictions.  I would feed the output to our dealing machine and no one would know where the special hands are.
    b) introduce the notion of a random rotation after the hand has been generated.  So, while the programatically, E might have a defined hand, after this random rotation any player might have that hand, but the full set of hands will be consistently oriented.
   c) Relate the notion of "dealer" to a) and b) above, so that depending on where the generated hand lands, (and the dealer position that is defined by that), I can control hand position relative to the dealer.

Given that context, I tried to download and build your stuff, but alas failed.   Suggestions?
You can email me at brian121@gmail.com.

thanks

Here is my output:

```
pi@Master-198:~ $ sudo python -mpip install --user git+https://github.com/anntzer/redeal
Downloading/unpacking git+https://github.com/anntzer/redeal
  Cloning https://github.com/anntzer/redeal to /tmp/pip-z1N6Rs-build
  Running setup.py (path:/tmp/pip-z1N6Rs-build/setup.py) egg_info for package from git+https://github.com/anntzer/redeal

Requirement already satisfied (use --upgrade to upgrade): colorama>=0.2.4 in /usr/lib/python2.7/dist-packages (from redeal==0.2.0)
Downloading/unpacking enum34>=1.0.4 (from redeal==0.2.0)
  Downloading enum34-1.1.6-py2-none-any.whl
Installing collected packages: enum34, redeal
  Running setup.py install for redeal
    g++ -fPIC -g -O3 -flto -fopenmp -mtune=generic -Wno-write-strings -Wshadow -Wsign-conversion -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=1 -Wswitch-default -Wundef -Werror -Wno-unused -Wno-unknown-pragmas -Wno-long-long -Wno-format  -c dds.cpp
    g++: error: unrecognized argument in option ‘-mtune=generic’
    g++: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale
    Makefiles/Makefile_linux_shared:96: recipe for target 'dds.o' failed
    make: *** [dds.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-z1N6Rs-build/setup.py", line 92, in <module>
        (["enum34>=1.0.4"] if sys.version_info < (3, 4) else [])
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-z1N6Rs-build/setup.py", line 58, in run
        ["make", "-f", "Makefiles/Makefile_linux_shared"])
      File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefiles/Makefile_linux_shared']' returned non-zero exit status 2
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-z1N6Rs-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hobZe_-record/install-record.txt --single-version-externally-managed --compile --user:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/redeal

copying redeal/__init__.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/__main__.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/gui.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/global_defs.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/redeal.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/smartstack.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/util.py -> build/lib.linux-armv7l-2.7/redeal

copying redeal/dds.py -> build/lib.linux-armv7l-2.7/redeal

g++ -fPIC -g -O3 -flto -fopenmp -mtune=generic -Wno-write-strings -Wshadow -Wsign-conversion -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wsign-promo -Wstrict-null-sentinel -Wstrict-overflow=1 -Wswitch-default -Wundef -Werror -Wno-unused -Wno-unknown-pragmas -Wno-long-long -Wno-format  -c dds.cpp

g++: error: unrecognized argument in option ‘-mtune=generic’

g++: note: valid arguments to ‘-mtune=’ are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a8 cortex-a9 cortex-m0 cortex-m0plus cortex-m1 cortex-m3 cortex-m4 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xscale

Makefiles/Makefile_linux_shared:96: recipe for target 'dds.o' failed

make: *** [dds.o] Error 1

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-z1N6Rs-build/setup.py", line 92, in <module>

    (["enum34>=1.0.4"] if sys.version_info < (3, 4) else [])

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/tmp/pip-z1N6Rs-build/setup.py", line 58, in run

    ["make", "-f", "Makefiles/Makefile_linux_shared"])

  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['make', '-f', 'Makefiles/Makefile_linux_shared']' returned non-zero exit status 2

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-z1N6Rs-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hobZe_-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-z1N6Rs-build
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/pip/__main__.py", line 5, in <module>
    exit = run()
  File "/usr/lib/python2.7/dist-packages/pip/runner.py", line 12, in run
    return pip.main()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 48: ordinal not in range(128)
```

**Comment by anntzer** [comment]
That appears to be an issue upstream with building the dds library.  You should open an issue at https://github.com/dds-bridge/dds to ask them for a Makefile that works on Raspberry (namely dds appears to force -mtune=native which appears not supported on non-x86 platforms(?)), this is not something that can be fixed on this side.

**Comment by anntzer** [comment]
Given the lack of action on dds' side, I just added a patch that passes $CFLAGS down to the dds makefile, so you should be able to do e.g. `CFLAGS=-mtune=native pip install ...`.  Can you have a look?

**Comment by anntzer** [comment]
I'll close given the lack of activity, feel free to reopen with more.
