### ISSUE TITLE
problems running on linux 

### ISSUE THREAD

**Issue by defiant** [anntzer/redeal#2]
I'm trying to run this on linux (Ubuntu) following the install instructions.

However /.setup.py gives  the following errors with build and install parameters;

```
running build
running build_py
Traceback (most recent call last):
  File "./setup.py", line 55, in <module>
    requires=["colorama (>=0.2.4)"]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./setup.py", line 30, in run
    super(make_build, self).run()
TypeError: must be type, not classobj
```

**Comment by anntzer** [comment]
Clearly I need to remember to test on Python2...
